version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5439:5439
    networks:
      - local-keycloak
    volumes:
      - db:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_PASSWORD: 1234
      KC_DB_USERNAME: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    ports:
      - 8082:8080
    restart: unless-stopped
    networks:
      - local-keycloak

  mongo:
    image: mongo:latest
    container_name: local_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_DATABASE: rootdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - local-keycloak
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mysql:
    image: mysql:latest
    container_name: local_mysql
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: facturacion-service
        MYSQL_USER: user-bill
        MYSQL_PASSWORD: password-bill
        MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  local-keycloak:

volumes:
  db: