server:
  port: 8086

spring:
  application:
    name: ms-bill
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/facturacion-service
    username: user-bill
    password: password-bill
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/DigitalMedia
            token-uri: http://localhost:8082/realms/DigitalMedia/protocol/openid-connect/token
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: microservicios
            client-secret: o4qr0tJsbARPAGvPunIJ1RtY0VKZ4EQK
            scope: openid
            redirect_uri: http://localhost:8086/login/oauth2/code/keycloak

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/